### ISSUE TITLE
mobile support

### ISSUE THREAD

**Issue by tilda** [xshotD/xshotD.github.io#3]
many people have complained about the way I just hate on mobile basically, so we have 2 options:
1. tell mobile users "no u"
2. go through some effort to make the page viewable
i'm leaning towards 1 since I really don't want to try and make media queries because I'll fail.
if $someone_who_views_this_issue wants to go ahead and do it for me, sure

**Comment by kotx** [comment]
no u

**Comment by tilda** [comment]
no u

**Comment by tilda** [comment]
closed bc moving to gitlab
